pair = 'BTCUSDT'
symbol = 'BTCUSDT'
qty = 0.012 #QTY for Futures

price_processed = {} #dictionary
minutes_processed = {} #dictionary
minute_candlesticks = [] #list
seconds_processed = {} 
second_candlesticks = []
price_diff = []
current_tick = None
previous_tick = None
closeRSI = []
RSI_float = []
closeRSI_TP = 0
num_trades = 0
RSI_60_SUM = 0
RSI6_SUM = 0
RSI12_SUM = 0
RSI24_SUM = 0
status = ""
# entry_price = 0
exit_price = 0
open_price = 0
close_price = 0
price_diff = 0
intrade = "NO"
entry_pos = None